Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Style/NegatedIf:
  Enabled: false  
Metrics/BlockLength:
  Max: 30
  ExcludedMethods:
    - RSpec.describe